baseurl = "https://opensourceinnovation.eu/"
DefaultContentLanguage = "en"
title = "Open Research Webinars"
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
disableKinds = []
themesDir = "node_modules/"
enableRobotsTXT = true
pluralizeListTitles = false
buildFuture = true # A new event website will always be in the future

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "Through a selection of state-of-the-art project presentations and demonstrations, this new series of webinars introduces software research projects that help shape the future of open source software and the IT industry. Co-organized and presented by OW2 and the Eclipse Foundation, they will focus on how multinational partners leverage open source in European publicly-funded collaborative research and innovation programs."
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["research event", "Open Research Webinars"]
  logo = "images/logo/Eclipse-Research-Logo-Stacked-Grey.jpg"
  #secondLogo = "images/logo/ow2.png"
  secondLogo = "images/logo/ow2-logo-square.png"
  logo_width = 100
  tagline = "Open Collaboration in European Research Projects"
  styles = "css/styles.css"
# favicon = ""
# share_img = ""
  gcse = "011805775785170369411:p3ec0igo0qq"
  js = "js/solstice.js?v1"
  featured_content_publish_target = "eclipse_org"

[taxonomies]

[Author]
  name = "Philippe Krief"
  website = "https://opensourceinnovation.eu"
  email = "webdev@eclipse-foundation.org"
  facebook = 
  twitter = 
  youtube = 
  googleplus = 
  linkedin = 

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

# [[menu.main]]
#     name = "Projects"
#     url = "https://www.eclipse.org/projects/"
#     weight = 1

# [[menu.main]]
#     name = "Working Groups"
#     url = "https://www.eclipse.org/org/workinggroups/"
#     weight = 2

# [[menu.main]]
#     name = "Members"
#     url = "https://www.eclipse.org/membership/"
#     weight = 3